'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {supabaseBrowser} from '@/lib/supabase-browser';
import styles from './AdminPanel.module.css';

type Tab='products'|'orders'|'installments'|'customers'|'conversations'|'reviews'|'homepage'|'settings'|'assets'|'audit';
type Product={id:string;name:string;model:string|null;price_usd:number|null;price_syp:number|null;stock_quantity:number;stock_status:string|null;is_active:boolean;is_featured:boolean;slug:string};
type Setting={key:string;value:any};
const tabs:[Tab,string][]=[['products','المنتجات'],['orders','الطلبات'],['installments','التقسيط'],['customers','العملاء'],['conversations','المحادثات'],['reviews','التقييمات'],['homepage','الرئيسية'],['settings','الإعدادات'],['assets','الأصول'],['audit','السجل']];

export default function AdminPanel(){
 const [mode,setMode]=useState<'login'|'dashboard'>('login');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [tab,setTab]=useState<Tab>('products');
 const [products,setProducts]=useState<Product[]>([]);const [settings,setSettings]=useState<Setting[]>([]);const [orders,setOrders]=useState<any[]>([]);const [plans,setPlans]=useState<any[]>([]);const [customers,setCustomers]=useState<any[]>([]);const [conversations,setConversations]=useState<any[]>([]);const [reviews,setReviews]=useState<any[]>([]);const [assets,setAssets]=useState<any[]>([]);const [audit,setAudit]=useState<any[]>([]);const [query,setQuery]=useState('');const [saving,setSaving]=useState(false);
 const getSetting=(key:string)=>settings.find(s=>s.key===key)?.value||{};const store=getSetting('store');const exchange=getSetting('exchange_rate');const showcase=getSetting('homepage_showcase');
 const productMap=useMemo(()=>new Map(products.map(p=>[p.id,p])),[products]);const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?products.filter(p=>`${p.name} ${p.model||''}`.toLowerCase().includes(q)):products},[products,query]);
 useEffect(()=>{let active=true;supabaseBrowser.auth.getUser().then(async({data})=>{if(!active||!data.user)return;const {data:a}=await supabaseBrowser.from('admins').select('id,is_active').eq('id',data.user.id).maybeSingle();if(a?.is_active){setMode('dashboard');await loadAll();}});return()=>{active=false}},[]);
 async function loadAll(){const [p,o,pl,c,cv,r,s,a,l]=await Promise.all([supabaseBrowser.from('products').select('id,name,model,price_usd,price_syp,stock_quantity,stock_status,is_active,is_featured,slug').order('updated_at',{ascending:false}).limit(300),supabaseBrowser.from('orders').select('*').order('created_at',{ascending:false}).limit(200),supabaseBrowser.from('installment_plans').select('*').order('updated_at',{ascending:false}).limit(200),supabaseBrowser.from('customers').select('*').order('created_at',{ascending:false}).limit(200),supabaseBrowser.from('conversations').select('*').order('last_message_at',{ascending:false}).limit(100),supabaseBrowser.from('reviews').select('*').order('created_at',{ascending:false}).limit(200),supabaseBrowser.from('settings').select('key,value').order('key'),supabaseBrowser.from('site_assets').select('*').order('key'),supabaseBrowser.from('audit_logs').select('*').order('created_at',{ascending:false}).limit(100)]);setProducts(p.data||[]);setOrders(o.data||[]);setPlans(pl.data||[]);setCustomers(c.data||[]);setConversations(cv.data||[]);setReviews(r.data||[]);setSettings(s.data||[]);setAssets(a.data||[]);setAudit(l.data||[]);const first=[p,o,pl,c,cv,r,s,a,l].find(x=>x.error);if(first?.error)setError(first.error.message);}
 async function login(e:FormEvent){e.preventDefault();setBusy(true);setError('');const {data,error:e1}=await supabaseBrowser.auth.signInWithPassword({email,password});if(e1||!data.user){setError(e1?.message||'تعذر تسجيل الدخول.');setBusy(false);return;}const {data:a,error:e2}=await supabaseBrowser.from('admins').select('id,is_active').eq('id',data.user.id).maybeSingle();if(e2||!a?.is_active){await supabaseBrowser.auth.signOut();setError('الحساب غير مخول.');setBusy(false);return;}setMode('dashboard');await loadAll();setBusy(false);}
 async function logout(){await supabaseBrowser.auth.signOut();setMode('login');}
 async function saveProduct(id:string,patch:Partial<Product>){setSaving(true);const {data,e}=await supabaseBrowser.from('products').update(patch).eq('id',id).select('id,name,model,price_usd,price_syp,stock_quantity,stock_status,is_active,is_featured,slug').single();if(e||!data)setError(e?.message||'تعذر الحفظ');else setProducts(v=>v.map(x=>x.id===id?data:x));setSaving(false);}
 async function saveSetting(key:string,value:any){setSaving(true);const {data,e}=await supabaseBrowser.from('settings').upsert({key,value,updated_at:new Date().toISOString()},{onConflict:'key'}).select('key,value').single();if(e||!data)setError(e?.message||'تعذر حفظ الإعداد');else setSettings(v=>[...v.filter(x=>x.key!==key),data]);setSaving(false);}
 async function saveOrder(id:string,status:string){setSaving(true);const {data,e}=await supabaseBrowser.from('orders').update({status}).eq('id',id).select('*').single();if(e||!data)setError(e?.message||'تعذر تحديث الطلب');else setOrders(v=>v.map(x=>x.id===id?data:x));setSaving(false);}
 async function setReview(id:string,value:boolean){const {error:e}=await supabaseBrowser.from('reviews').update({is_approved:value}).eq('id',id);if(e)setError(e.message);else setReviews(v=>v.map(x=>x.id===id?{...x,is_approved:value}:x));}
 if(mode==='login')return <main className={styles.page}><div className={`${styles.card} ${styles.loginCard}`}><div className="eyebrow">LOUAY PHONE · ADMIN</div><h1>لوحة التحكم</h1><p>إدارة المتجر والإعدادات والطلبات من مكان واحد.</p><form className={styles.form} onSubmit={login}><label>البريد الإلكتروني<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email"/></label><label>كلمة المرور<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/></label>{error&&<div className={styles.error}>{error}</div>}<button className={`btn btn--dark ${styles.submit}`} disabled={busy}>{busy?'جارٍ الدخول…':'دخول'}</button></form></div></main>;
 return <main className={styles.page}><div className={styles.shell}><header className={styles.header}><div><div className="eyebrow">LOUAY PHONE · CONTROL CENTER</div><h1>إدارة المتجر</h1><p>التحكم بالمنتجات والصور والأسعار والطلبات والمحتوى والإعدادات.</p></div><div className={styles.headerActions}><Link href="/" className="btn btn--link">فتح المتجر</Link><button className="btn btn--dark" onClick={logout}>خروج</button></div></header><nav className={styles.tabs} aria-label="أقسام الإدارة">{tabs.map(([id,label])=><button key={id} className={`${styles.tab} ${tab===id?styles.tabActive:''}`} onClick={()=>{setTab(id);setQuery('')}}>{label}</button>)}</nav>{error&&<div className={styles.error}>{error}</div>}
 {tab==='products'&&<section><div className={styles.toolbar}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث عن هاتف أو موديل…"/><span>{filtered.length} منتج</span></div><div className={styles.products}>{filtered.map(p=><article className={styles.row} key={p.id}><div className={styles.main}><strong>{p.name}</strong><span>{p.model||'بدون موديل'}</span></div><label>USD<input value={p.price_usd??''} onChange={e=>setProducts(v=>v.map(x=>x.id===p.id?{...x,price_usd:e.target.value===''?null:Number(e.target.value)}:x))} onBlur={()=>saveProduct(p.id,{price_usd:p.price_usd})}/></label><label>المخزون<input value={p.stock_quantity} onChange={e=>setProducts(v=>v.map(x=>x.id===p.id?{...x,stock_quantity:Number(e.target.value||0)}:x))} onBlur={()=>saveProduct(p.id,{stock_quantity:p.stock_quantity})}/></label><label>الظهور<button className={`${styles.toggle} ${p.is_active?styles.toggleOn:''}`} disabled={saving} onClick={()=>saveProduct(p.id,{is_active:!p.is_active})}>{p.is_active?'ظاهر':'مخفي'}</button></label><label>مميز<button className={`${styles.toggle} ${p.is_featured?styles.toggleFeatured:''}`} disabled={saving} onClick={()=>saveProduct(p.id,{is_featured:!p.is_featured})}>{p.is_featured?'مميز':'عادي'}</button></label><Link className="btn btn--link" href={`/admin/media/${p.id}`}>إدارة الصور</Link></article>)}</div></section>}
 {tab==='orders'&&<section className={styles.list}>{orders.map(o=><article className={styles.panelRow} key={o.id}><div><strong>طلب {String(o.id).slice(0,8)}</strong><span>{o.product_id?productMap.get(o.product_id)?.name||'منتج':'—'}</span></div><span>{o.total_amount??'—'}</span><select value={o.status} onChange={e=>saveOrder(o.id,e.target.value)} disabled={saving}><option value="new">جديد</option><option value="reviewing">قيد المراجعة</option><option value="contacted">تم التواصل</option><option value="confirmed">مؤكد</option><option value="cancelled">ملغى</option></select></article>)}</section>}
 {tab==='installments'&&<section className={styles.list}>{plans.map(p=><article className={styles.panelRow} key={p.id}><div><strong>{productMap.get(p.product_id)?.name||String(p.product_id).slice(0,8)}</strong><span>{p.months} شهر · {p.first_payment_type==='percentage'?'نسبة':'مبلغ'} {p.first_payment_value}</span></div><span>شهري {p.monthly_amount??'—'}</span><button className={`${styles.toggle} ${p.is_active?styles.toggleOn:''}`} onClick={async()=>{const {error:e}=await supabaseBrowser.from('installment_plans').update({is_active:!p.is_active}).eq('id',p.id);if(e)setError(e.message);else setPlans(v=>v.map(x=>x.id===p.id?{...x,is_active:!x.is_active}:x));}}>{p.is_active?'مفعل':'متوقف'}</button></article>)}</section>}
 {tab==='customers'&&<section className={styles.list}>{customers.map(c=><article className={styles.panelRow} key={c.id}><div><strong>{c.name}</strong><span>{c.phone}</span></div><span>{c.address||'بدون عنوان'}</span><span>{c.telegram_username?`@${c.telegram_username}`:'—'}</span></article>)}</section>}
 {tab==='conversations'&&<section className={styles.list}>{conversations.map(c=><article className={styles.panelRow} key={c.id}><div><strong>{c.ticket_code||String(c.id).slice(0,8)}</strong><span>{c.visitor_name||'زائر'}</span></div><span>{c.status}</span><span>{new Date(c.last_message_at).toLocaleString('ar-SY')}</span></article>)}</section>}
 {tab==='reviews'&&<section className={styles.list}>{reviews.map(r=><article className={styles.panelRow} key={r.id}><div><strong>{r.customer_name}</strong><span>{productMap.get(r.product_id)?.name||'منتج'}</span></div><span>{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)}</span><button className={`${styles.toggle} ${r.is_approved?styles.toggleOn:''}`} onClick={()=>setReview(r.id,!r.is_approved)}>{r.is_approved?'معروض':'قيد المراجعة'}</button></article>)}</section>}
 {tab==='homepage'&&<section className={styles.grid}><div className={styles.card}><div className="eyebrow">HERO</div><h2>اختيار صورة البطل</h2><select value={showcase.hero_product_id||''} onChange={e=>saveSetting('homepage_showcase',{...showcase,hero_product_id:e.target.value||null})}><option value="">اختيار تلقائي</option>{products.filter(p=>p.is_active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><p>اختر المنتج الذي تريد أن يقود الصفحة الرئيسية.</p></div><div className={styles.card}><div className="eyebrow">FEATURED</div><h2>الهواتف المميزة</h2><div className={styles.checkGrid}>{products.filter(p=>p.is_active).slice(0,80).map(p=><label key={p.id} className={styles.check}><input type="checkbox" checked={(showcase.featured_product_ids||[]).includes(p.id)} onChange={e=>{const current=showcase.featured_product_ids||[];const next=e.target.checked?[...current,p.id]:current.filter((id:string)=>id!==p.id);if(next.length<=6)saveSetting('homepage_showcase',{...showcase,featured_product_ids:next});}}/><span>{p.name}</span></label>)}</div></div></section>}
 {tab==='settings'&&<section className={styles.settingsGrid}><div className={styles.card}><div className="eyebrow">STORE</div><h2>معلومات المتجر</h2><label>اسم المتجر<input defaultValue={store.name||'Louay Phone'} onBlur={e=>saveSetting('store',{...store,name:e.target.value})}/></label><label>العملة الأساسية<input defaultValue={store.currency||'SYP'} onBlur={e=>saveSetting('store',{...store,currency:e.target.value.toUpperCase()})}/></label><label>العملة الثانوية<input defaultValue={store.secondary_currency||'USD'} onBlur={e=>saveSetting('store',{...store,secondary_currency:e.target.value.toUpperCase()})}/></label></div><div className={styles.card}><div className="eyebrow">EXCHANGE RATE</div><h2>سعر الصرف</h2><p>تعديل إداري فقط. تغيير هذه القيمة لا يعدّل أسعار المنتجات تلقائيًا.</p><div className={styles.rateBox}><input defaultValue={exchange.usd_to_syp??''} inputMode="decimal"/><span>{store.currency||'SYP'} لكل 1 USD</span></div><button className="btn btn--dark" onClick={e=>{const input=(e.currentTarget.parentElement?.querySelector('input') as HTMLInputElement);void saveSetting('exchange_rate',{usd_to_syp:Number(input?.value||0)})}} disabled={saving}>حفظ سعر الصرف</button></div></section>}
 {tab==='assets'&&<section className={styles.list}>{assets.map(a=><article className={styles.panelRow} key={a.key}><div><strong>{a.key}</strong><span>{a.mime_type||'asset'}</span></div><a href={a.url} target="_blank" rel="noreferrer" className="btn btn--link">فتح الأصل</a></article>)}</section>}
 {tab==='audit'&&<section className={styles.list}>{audit.length?audit.map(a=><article className={styles.panelRow} key={a.id}><div><strong>{a.action}</strong><span>{a.entity}</span></div><span>{a.entity_id?String(a.entity_id).slice(0,8):'—'}</span><span>{new Date(a.created_at).toLocaleString('ar-SY')}</span></article>):<div className={styles.card}><h2>سجل العمليات فارغ</h2><p>سيبدأ الظهور عند تسجيل أحداث التدقيق في النظام.</p></div>}</section>}
 </div></main>;
}
