'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { supabaseBrowser } from '@/lib/supabase-browser';
import styles from './AdminPanel.module.css';

type Tab = 'products' | 'orders' | 'installments' | 'customers' | 'conversations' | 'reviews' | 'homepage' | 'settings' | 'assets' | 'audit';
type Product = { id:string; name:string; model:string|null; price_usd:number|null; price_syp:number|null; stock_quantity:number; stock_status:string|null; is_active:boolean; is_featured:boolean; installment_enabled:boolean; brand_id:string|null; slug:string };
type Order = { id:string; status:string; notes:string|null; total_amount:number|null; first_payment:number|null; monthly_amount:number|null; months:number|null; customer_id:string|null; product_id:string|null; installment_plan_id:string|null; created_at:string };
type Plan = { id:string; product_id:string; months:number; first_payment_type:string; first_payment_value:number; total_price:number|null; monthly_amount:number|null; is_active:boolean };
type Customer = { id:string; name:string; phone:string; address:string|null; telegram_username:string|null; created_at:string };
type Conversation = { id:string; ticket_code:string|null; visitor_name:string|null; status:string; last_message_at:string; customer_id:string|null; telegram_chat_id:number|null };
type Review = { id:string; product_id:string; customer_name:string; rating:number; comment:string|null; is_approved:boolean; created_at:string };
type Asset = { key:string; url:string; mime_type:string|null; version:number|null };
type Setting = { key:string; value:Record<string, unknown> };

const tabs: [Tab,string][] = [
  ['products','المنتجات'],['orders','الطلبات'],['installments','التقسيط'],['customers','العملاء'],['conversations','المحادثات'],['reviews','التقييمات'],['homepage','الرئيسية'],['settings','الإعدادات'],['assets','الأصول'],['audit','السجل']
];

export default function AdminPanel(){
  const [mode,setMode]=useState<'login'|'dashboard'>('login');
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [tab,setTab]=useState<Tab>('products');
  const [products,setProducts]=useState<Product[]>([]); const [orders,setOrders]=useState<Order[]>([]); const [plans,setPlans]=useState<Plan[]>([]); const [customers,setCustomers]=useState<Customer[]>([]); const [conversations,setConversations]=useState<Conversation[]>([]); const [reviews,setReviews]=useState<Review[]>([]); const [settings,setSettings]=useState<Setting[]>([]); const [assets,setAssets]=useState<Asset[]>([]); const [audit,setAudit]=useState<{id:string;action:string;entity:string;entity_id:string|null;created_at:string}[]>([]); const [query,setQuery]=useState(''); const [saving,setSaving]=useState(false);

  useEffect(()=>{ let mounted=true; supabaseBrowser.auth.getUser().then(async({data})=>{ if(!mounted||!data.user) return; const {data:admin}=await supabaseBrowser.from('admins').select('id,is_active').eq('id',data.user.id).maybeSingle(); if(admin?.is_active){setMode('dashboard'); await loadAll();} }); return()=>{mounted=false}; },[]);

  async function loadAll(){ setError(''); const [p,o,pl,c,cv,r,s,a,al]=await Promise.all([
    supabaseBrowser.from('products').select('id,name,model,price_usd,price_syp,stock_quantity,stock_status,is_active,is_featured,installment_enabled,brand_id,slug').order('updated_at',{ascending:false}).limit(250),
    supabaseBrowser.from('orders').select('id,status,notes,total_amount,first_payment,monthly_amount,months,customer_id,product_id,installment_plan_id,created_at').order('created_at',{ascending:false}).limit(200),
    supabaseBrowser.from('installment_plans').select('id,product_id,months,first_payment_type,first_payment_value,total_price,monthly_amount,is_active').order('updated_at',{ascending:false}).limit(200),
    supabaseBrowser.from('customers').select('id,name,phone,address,telegram_username,created_at').order('created_at',{ascending:false}).limit(200),
    supabaseBrowser.from('conversations').select('id,ticket_code,visitor_name,status,last_message_at,customer_id,telegram_chat_id').order('last_message_at',{ascending:false}).limit(100),
    supabaseBrowser.from('reviews').select('id,product_id,customer_name,rating,comment,is_approved,created_at').order('created_at',{ascending:false}).limit(200),
    supabaseBrowser.from('settings').select('key,value').order('key'),
    supabaseBrowser.from('site_assets').select('key,url,mime_type,version').order('key'),
    supabaseBrowser.from('audit_logs').select('id,action,entity,entity_id,created_at').order('created_at',{ascending:false}).limit(100),
  ]); setProducts((p.data??[]) as Product[]); setOrders((o.data??[]) as Order[]); setPlans((pl.data??[]) as Plan[]); setCustomers((c.data??[]) as Customer[]); setConversations((cv.data??[]) as Conversation[]); setReviews((r.data??[]) as Review[]); setSettings((s.data??[]) as Setting[]); setAssets((a.data??[]) as Asset[]); setAudit((al.data??[]) as typeof audit); const first=[p,o,pl,c,cv,r,s,a,al].find(x=>x.error); if(first?.error) setError(first.error.message); }

  async function login(e:FormEvent){e.preventDefault();setBusy(true);setError('');const {data,error:loginError}=await supabaseBrowser.auth.signInWithPassword({email,password});if(loginError||!data.user){setBusy(false);setError(loginError?.message??'تعذر تسجيل الدخول.');return;}const {data:admin,error:adminError}=await supabaseBrowser.from('admins').select('id,is_active').eq('id',data.user.id).maybeSingle();if(adminError||!admin?.is_active){await supabaseBrowser.auth.signOut();setBusy(false);setError('هذا الحساب غير مخوّل لإدارة المتجر.');return;}setMode('dashboard');await loadAll();setBusy(false);}
  async function logout(){await supabaseBrowser.auth.signOut();setMode('login');}

  async function updateProduct(id:string,patch:Partial<Product>){setSaving(true);const {data,error:e}=await supabaseBrowser.from('products').update(patch).eq('id',id).select('id,name,model,price_usd,price_syp,stock_quantity,stock_status,is_active,is_featured,installment_enabled,brand_id,slug').single();if(e||!data)setError(e?.message??'تعذر الحفظ');else setProducts(v=>v.map(x=>x.id===id?data as Product:x));setSaving(false);}
  async function updateOrder(id:string,status:string){setSaving(true);const {data,e}=await (async()=>{const r=await supabaseBrowser.from('orders').update({status}).eq('id',id).select('id,status,notes,total_amount,first_payment,monthly_amount,months,customer_id,product_id,installment_plan_id,created_at').single();return {data:r.data,e:r.error}})();if(e||!data)setError(e?.message??'تعذر تحديث الطلب');else setOrders(v=>v.map(x=>x.id===id?data as Order:x));setSaving(false);}
  async function approveReview(id:string,is_approved:boolean){const {error:e}=await supabaseBrowser.from('reviews').update({is_approved}).eq('id',id);if(e)setError(e.message);else setReviews(v=>v.map(x=>x.id===id?{...x,is_approved}:x));}
  async function updateConversation(id:string,status:string){const {error:e}=await supabaseBrowser.from('conversations').update({status}).eq('id',id);if(e)setError(e.message);else setConversations(v=>v.map(x=>x.id===id?{...x,status}:x));}

  const productMap=useMemo(()=>new Map(products.map(p=>[p.id,p])),[products]);
  const filteredProducts=useMemo(()=>{const q=query.trim().toLowerCase();return q?products.filter(p=>`${p.name} ${p.model??''}`.toLowerCase().includes(q)):products},[products,query]);
  const setting=(key:string)=>settings.find(s=>s.key===key)?.value;
  const showcase=setting('homepage_showcase') as {hero_product_id?:string;featured_product_ids?:string[]} | undefined;
  const store=setting('store') as {name?:string;currency?:string;secondary_currency?:string} | undefined;
  const exchange=setting('exchange_rate') as {usd_to_syp?:number} | undefined;

  if(mode==='login') return <main className={styles.page}><div className={`${styles.card} ${styles.loginCard}`}><div className="eyebrow">LOUAY PHONE · ADMIN</div><h1>لوحة التحكم</h1><p>دخول آمن لإدارة المتجر وبياناته.</p><form onSubmit={login} className={styles.form}><label>البريد الإلكتروني<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></label><label>كلمة المرور<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label>{error&&<div className={styles.error} role="alert">{error}</div>}<button className={`btn btn--dark ${styles.submit}`} disabled={busy}>{busy?'جارٍ الدخول…':'دخول'}</button></form></div></main>;

  return <main className={styles.page}><div className={styles.shell}><header className={styles.header}><div><div className="eyebrow">LOUAY PHONE · CONTROL CENTER</div><h1>إدارة المتجر</h1><p>كل جداول Supabase المهمة أصبحت أمامك في مكان واحد.</p></div><div className={styles.headerActions}><Link className="btn btn--link" href="/">فتح المتجر</Link><button className="btn btn--dark" onClick={logout}>تسجيل الخروج</button></div></header>
    <nav className={styles.tabs} aria-label="أقسام الإدارة">{tabs.map(([id,label])=><button key={id} className={`${styles.tab} ${tab===id?styles.tabActive:''}`} onClick={()=>{setTab(id);setQuery('')}}>{label}</button>)}</nav>
    {error&&<div className={styles.error} role="alert">{error}</div>}
    {tab==='products'&&<section><div className={styles.toolbar}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث عن هاتف أو موديل…"/><span>{filteredProducts.length} منتج</span></div><div className={styles.products}>{filteredProducts.map(p=><article className={styles.row} key={p.id}><div className={styles.main}><strong>{p.name}</strong><span>{p.model??'بدون موديل'}</span></div><label>USD<input inputMode="decimal" value={p.price_usd??''} onChange={e=>setProducts(v=>v.map(x=>x.id===p.id?{...x,price_usd:e.target.value===''?null:Number(e.target.value)}:x))} onBlur={()=>updateProduct(p.id,{price_usd:p.price_usd})}/></label><label>المخزون<input inputMode="numeric" value={p.stock_quantity} onChange={e=>setProducts(v=>v.map(x=>x.id===p.id?{...x,stock_quantity:Number(e.target.value||0)}:x))} onBlur={()=>updateProduct(p.id,{stock_quantity:p.stock_quantity})}/></label><label>الظهور<button className={`${styles.toggle} ${p.is_active?styles.toggleOn:''}`} disabled={saving} onClick={()=>updateProduct(p.id,{is_active:!p.is_active})}>{p.is_active?'ظاهر':'مخفي'}</button></label><label>مميز<button className={`${styles.toggle} ${p.is_featured?styles.toggleFeatured:''}`} disabled={saving} onClick={()=>updateProduct(p.id,{is_featured:!p.is_featured})}>{p.is_featured?'مميز':'عادي'}</button></label></article>)}</div></section>}
    {tab==='orders'&&<section className={styles.list}>{orders.map(o=><article className={styles.panelRow} key={o.id}><div><strong>طلب {o.id.slice(0,8)}</strong><span>{new Date(o.created_at).toLocaleString('ar-SY')}</span></div><span>{o.product_id?productMap.get(o.product_id)?.name??'منتج':''}</span><span>{o.total_amount??'—'}</span><select value={o.status} onChange={e=>updateOrder(o.id,e.target.value)} disabled={saving}><option value="new">جديد</option><option value="reviewing">قيد المراجعة</option><option value="contacted">تم التواصل</option><option value="confirmed">مؤكد</option><option value="cancelled">ملغى</option></select></article>)}</section>}
    {tab==='installments'&&<section className={styles.list}>{plans.map(pl=><article className={styles.panelRow} key={pl.id}><div><strong>{productMap.get(pl.product_id)?.name??pl.product_id.slice(0,8)}</strong><span>{pl.months} شهر · {pl.first_payment_type==='percentage'?'نسبة':'مبلغ'} {pl.first_payment_value}</span></div><span>إجمالي {pl.total_price??'—'}</span><span>شهري {pl.monthly_amount??'—'}</span><button className={`${styles.toggle} ${pl.is_active?styles.toggleOn:''}`} onClick={async()=>{const {error:e}=await supabaseBrowser.from('installment_plans').update({is_active:!pl.is_active}).eq('id',pl.id);if(e)setError(e.message);else setPlans(v=>v.map(x=>x.id===pl.id?{...x,is_active:!x.is_active}:x));}}>{pl.is_active?'مفعل':'متوقف'}</button></article>)}</section>}
    {tab==='customers'&&<section className={styles.list}>{customers.map(c=><article className={styles.panelRow} key={c.id}><div><strong>{c.name}</strong><span>{c.phone}</span></div><span>{c.address??'بدون عنوان'}</span><span>{c.telegram_username?`@${c.telegram_username}`:'—'}</span><span>{new Date(c.created_at).toLocaleDateString('ar-SY')}</span></article>)}</section>}
    {tab==='conversations'&&<section className={styles.list}>{conversations.map(c=><article className={styles.panelRow} key={c.id}><div><strong>{c.ticket_code??c.id.slice(0,8)}</strong><span>{c.visitor_name??'زائر'}</span></div><span>{new Date(c.last_message_at).toLocaleString('ar-SY')}</span><select value={c.status} onChange={e=>updateConversation(c.id,e.target.value)}><option value="open">مفتوحة</option><option value="processing">قيد المعالجة</option><option value="closed">مغلقة</option></select></article>)}</section>}
    {tab==='reviews'&&<section className={styles.list}>{reviews.map(r=><article className={styles.panelRow} key={r.id}><div><strong>{r.customer_name}</strong><span>{productMap.get(r.product_id)?.name??'منتج'}</span></div><span>{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)}</span><span>{r.comment??'بدون تعليق'}</span><button className={`${styles.toggle} ${r.is_approved?styles.toggleOn:''}`} onClick={()=>approveReview(r.id,!r.is_approved)}>{r.is_approved?'معروض':'قيد المراجعة'}</button></article>)}</section>}
    {tab==='homepage'&&<section className={styles.grid}><div className={styles.card}><div className="eyebrow">HERO</div><h2>المنتج المختار</h2><p>{showcase?.hero_product_id?productMap.get(showcase.hero_product_id)?.name??'غير موجود ضمن القائمة الحالية':'غير محدد'}</p><small>المصدر: settings.homepage_showcase.hero_product_id</small></div><div className={styles.card}><div className="eyebrow">FEATURED</div><h2>المنتجات المميزة</h2><div className={styles.miniList}>{(showcase?.featured_product_ids??[]).map(id=><span key={id}>{productMap.get(id)?.name??id.slice(0,8)}</span>)}</div><small>المصدر: settings.homepage_showcase.featured_product_ids</small></div></section>}
    {tab==='settings'&&<section className={styles.grid}><div className={styles.card}><div className="eyebrow">STORE</div><h2>{store?.name??'Louay Phone'}</h2><p>العملة الأساسية: {store?.currency??'SYP'}</p><p>العملة الثانوية: {store?.secondary_currency??'USD'}</p></div><div className={styles.card}><div className="eyebrow">EXCHANGE RATE</div><h2>{exchange?.usd_to_syp??'—'}</h2><p>ل.س لكل دولار — القراءة الحالية فقط، لا يتم تعديلها تلقائيًا.</p></div></section>}
    {tab==='assets'&&<section className={styles.assetGrid}>{assets.map(a=><article className={styles.asset} key={a.key}>{a.mime_type?.startsWith('image/')?<img src={a.url} alt={a.key} loading="lazy"/>:<div className={styles.assetFile}>{a.mime_type}</div>}<strong>{a.key}</strong><small>v{a.version??'—'}</small></article>)}</section>}
    {tab==='audit'&&<section className={styles.list}>{audit.length?audit.map(a=><article className={styles.panelRow} key={a.id}><div><strong>{a.action}</strong><span>{a.entity}</span></div><span>{a.entity_id??'—'}</span><span>{new Date(a.created_at).toLocaleString('ar-SY')}</span></article>):<div className={styles.card}><h2>السجل فارغ حاليًا.</h2><p>سنستخدمه لتتبع تغييرات الإدارة مع توسع العمليات.</p></div>}</section>}
  </div></main>;
}
