import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import StoreHeader from '@/components/store/StoreHeader';
import { getCachedBrand, getCachedBrandProducts } from '@/lib/storefront-cache';
import { currentSyp, formatSyp, formatUsd, primaryProductImage, sortedProductImages } from '@/lib/storefront-format';

export const revalidate=600;
const PAGE_SIZE=9;
function clampPage(value:string|string[]|undefined){const n=Number(Array.isArray(value)?value[0]:value||1);return Number.isFinite(n)&&n>0?Math.floor(n):1}
function ProductCard({product,brand,rate}:{product:any;brand:any;rate:unknown}){const images=sortedProductImages(product.product_images);const primary=primaryProductImage(images);const secondary=images.find(image=>image.url!==primary?.url);const note=product.specs?.notes;const priceSyp=currentSyp(product.price_usd,product.price_syp,rate);return <Link href={`/product/${product.slug}`} className="group luxury-card overflow-hidden"><div className="product-media relative aspect-[4/4.1] overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_38%,rgba(120,216,255,.10),transparent_50%)]"/>{primary?.url?<>{secondary?<Image src={secondary.url} alt={secondary.alt_text??product.name} fill sizes="(max-width:640px) 100vw,(max-width:1024px) 50vw,33vw" loading="lazy" className="absolute inset-0 z-[8] object-contain p-6 opacity-0 transition duration-200 group-hover:opacity-100"/>:null}<Image src={primary.url} alt={primary.alt_text??product.name} fill sizes="(max-width:640px) 100vw,(max-width:1024px) 50vw,33vw" loading="lazy" className="relative z-10 object-contain p-6 transition duration-300 group-hover:scale-[1.02]"/></>:<div className="relative z-10 flex h-full flex-col items-center justify-center gap-3 p-6 text-center text-slate-500"><div className="flex h-14 w-14 items-center justify-center rounded-[1.15rem] border border-white/10 bg-white/[.03] text-xl text-sky-300">✦</div><span className="text-xs font-bold">الصورة ستُضاف لاحقًا</span></div>}{secondary?<span className="premium-card-gallery-hint absolute bottom-4 left-4 z-20 rounded-lg bg-black/50 px-2 py-1 text-[9px] font-bold text-slate-300">صور متعددة</span>:null}{product.installment_enabled?<span className="luxury-badge absolute right-4 top-4 z-20">تقسيط</span>:null}</div><div className="p-4 sm:p-5"><div className="flex items-center justify-between gap-3"><p className="text-[10px] font-extrabold uppercase tracking-[.14em] text-sky-300">{brand.name}</p>{product.stock_status==='in_stock'?<span className="text-[10px] font-bold text-emerald-300">متوفر</span>:null}</div><h2 className="mt-2 line-clamp-2 min-h-[3.2rem] text-[1rem] font-extrabold leading-6 tracking-tight text-white sm:text-[1.05rem]">{product.name}</h2>{(product.model||note)?<p className="mt-1 min-h-5 line-clamp-1 text-xs text-slate-500">{product.model&&product.model!=='-'?product.model:''}{note?` • ${note}`:''}</p>:null}<div className="luxury-divider my-3.5"/><div className="flex items-end justify-between gap-2"><div><b className="text-sm text-white sm:text-base">{formatSyp(priceSyp)}</b>{product.price_usd?<p className="mt-1 text-[11px] text-slate-500">{formatUsd(product.price_usd)}</p>:null}</div><span className="text-[11px] font-bold text-slate-500 transition group-hover:text-sky-300">التفاصيل ←</span></div></div></Link>}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const brand=await getCachedBrand(slug);if(!brand)return{title:'الماركة غير موجودة'};return{title:`${brand.name} — هواتف وأسعار`,description:`تصفح هواتف ${brand.name} المنشورة حاليًا في Louay Phone مع المواصفات والأسعار والطلب المباشر.`,alternates:{canonical:`/products/brand/${brand.slug}`},openGraph:{title:`${brand.name} | Louay Phone`,description:`هواتف ${brand.name} المتوفرة حاليًا في Louay Phone.`,type:'website'}}}
export default async function BrandPage({params,searchParams}:{params:Promise<{slug:string}>;searchParams?:Promise<{page?:string|string[]}>}){const {slug}=await params;const query=searchParams?await searchParams:{};const page=clampPage(query.page);const {brand,products,count,rate}=await getCachedBrandProducts(slug,page,PAGE_SIZE);if(!brand)notFound();const totalPages=Math.max(1,Math.ceil((count??0)/PAGE_SIZE));if(page>totalPages&&(count??0)>0)notFound();return <main data-storefront="true" className="storefront-catalog premium-catalog min-h-screen overflow-x-clip luxury-grid"><StoreHeader/><section className="mx-auto max-w-7xl px-4 pb-20 pt-8 sm:px-6 lg:px-8"><div className="mb-8 flex flex-wrap items-end justify-between gap-5"><div><Link href="/products" className="text-xs font-bold text-sky-300 transition hover:text-white">← الماركات</Link><p className="premium-eyebrow mt-7">THE COLLECTION</p><h1 className="mt-3 text-[2.7rem] font-black tracking-[-.05em] sm:text-6xl">{brand.name}</h1></div><span className="luxury-badge">{count??0} منتج</span></div>{(products??[]).length?<div className="catalog-products-grid">{products.map((product:any)=><ProductCard key={product.id} product={product} brand={brand} rate={rate}/>)}</div>:<div className="lp-surface rounded-3xl p-14 text-center text-slate-400">لا توجد هواتف منشورة لهذه الماركة حاليًا.</div>}{totalPages>1?<nav className="mt-10 flex flex-wrap items-center justify-center gap-2" aria-label="صفحات المنتجات">{page>1?<Link href={`/products/brand/${brand.slug}?page=${page-1}`} className="luxury-button-secondary">السابق</Link>:null}{Array.from({length:totalPages},(_,i)=>i+1).slice(Math.max(0,page-3),Math.min(totalPages,page+2)).map(n=><Link key={n} href={`/products/brand/${brand.slug}?page=${n}`} className={n===page?'luxury-button':'luxury-button-secondary'}>{n}</Link>)}{page<totalPages?<Link href={`/products/brand/${brand.slug}?page=${page+1}`} className="luxury-button-secondary">التالي</Link>:null}</nav>:null}</section></main>}
