import Link from 'next/link';
import Image from 'next/image';
import { Plus, Smartphone, Tags, Search } from 'lucide-react';
import { createClient } from '@/lib/supabase/server';
import AutoFillMissingImages from '@/components/admin/AutoFillMissingImages';

export default async function AdminProductsPage() {
  const supabase = await createClient();
  const { data: products } = await supabase.from('products').select('id,name,slug,price_usd,price_syp,stock_status,is_active,installment_enabled,brands(name),product_images(url,alt_text,is_primary,position)').order('created_at',{ascending:false});
  const rows = (products ?? []).map((p: any) => ({ ...p, image: [...(p.product_images ?? [])].sort((a:any,b:any)=>(Number(a.position)||0)-(Number(b.position)||0))[0] }));
  const missingImages = rows.filter((p: any) => !p.product_images?.length).length;
  return <section className="p-5 lg:p-10">
    <div className="mb-8 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black tracking-[.18em] text-sky-300">CATALOG CONTROL</p><h1 className="mt-2 text-3xl font-black tracking-tight">الهواتف</h1><p className="mt-2 text-sm text-slate-400">راجع الكتالوج، الصور، الأسعار، التقسيط والحالة قبل عرض المنتج للزبائن.</p></div><div className="flex flex-wrap gap-3"><Link href="/admin/brands" className="flex items-center gap-2 rounded-2xl border border-white/10 bg-white/[.03] px-4 py-3 text-sm font-bold text-slate-200 transition hover:border-sky-300/20 hover:bg-sky-400/[.05]"><Tags size={18}/> صور الماركات</Link><Link href="/admin/products/new" className="flex items-center gap-2 rounded-2xl bg-gradient-to-r from-sky-300 to-sky-500 px-4 py-3 font-black text-slate-950 shadow-lg shadow-sky-500/10 transition hover:-translate-y-0.5"><Plus size={18}/> إضافة هاتف</Link></div></div>
    <AutoFillMissingImages />
    <div className="mb-5 grid gap-3 sm:grid-cols-4"><div className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><p className="text-xs text-slate-500">إجمالي الهواتف</p><b className="mt-1 block text-2xl">{rows.length}</b></div><div className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><p className="text-xs text-slate-500">نشطة</p><b className="mt-1 block text-2xl text-emerald-300">{rows.filter((p:any)=>p.is_active).length}</b></div><div className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><p className="text-xs text-slate-500">متوفرة</p><b className="mt-1 block text-2xl text-sky-300">{rows.filter((p:any)=>p.stock_status==='in_stock').length}</b></div><div className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><p className="text-xs text-slate-500">بلا صور</p><b className="mt-1 block text-2xl text-amber-300">{missingImages}</b></div></div>
    <div className="mb-5 flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[.025] px-4 py-3 text-sm text-slate-500"><Search size={18}/><span>استخدم بحث المتصفح للعثور على هاتف بسرعة، أو افتح المنتج لاستخدام البحث الذكي عن الصور.</span></div>
    <div className="overflow-hidden rounded-[1.5rem] border border-white/10 bg-white/[.02] shadow-2xl shadow-black/20"><div className="hidden grid-cols-[1fr_160px_130px_110px] gap-4 border-b border-white/10 bg-black/10 p-4 text-xs font-bold text-slate-500 md:grid"><span>الهاتف</span><span>السعر</span><span>المخزون</span><span>الحالة</span></div>{rows.map((p:any)=><Link key={p.id} href={`/admin/products/${p.id}`} className="grid gap-4 border-b border-white/[.06] p-4 transition hover:bg-sky-400/[.035] md:grid-cols-[1fr_160px_130px_110px] md:items-center"><div className="flex min-w-0 items-center gap-3"><div className="relative h-14 w-14 shrink-0 overflow-hidden rounded-2xl border border-white/10 bg-[#0b1016]">{p.image?.url ? <Image src={p.image.url} alt={p.image.alt_text ?? p.name} fill sizes="56px" className="object-contain p-1" /> : <div className="grid h-full place-items-center text-sky-300"><Smartphone size={19}/></div>}</div><div className="min-w-0"><p className="truncate font-black">{p.name}</p><p className="mt-1 truncate text-xs text-slate-500">{p.brands?.name ?? 'بدون ماركة'}{p.installment_enabled ? ' • تقسيط' : ''}</p></div></div><div><b>{p.price_syp ? Number(p.price_syp).toLocaleString('ar-SY') : '—'}</b><p className="mt-1 text-xs text-slate-500">{p.price_usd ? `$${p.price_usd}` : ''}</p></div><span className={`text-sm font-bold ${p.stock_status === 'in_stock' ? 'text-emerald-300' : p.stock_status === 'out_of_stock' ? 'text-red-300' : 'text-amber-300'}`}>{p.stock_status === 'in_stock' ? 'متوفر' : p.stock_status === 'out_of_stock' ? 'غير متوفر' : 'قريبًا'}</span><span className={p.is_active ? 'text-sm font-bold text-emerald-300' : 'text-sm font-bold text-red-300'}>{p.is_active ? 'نشط' : 'مخفي'}</span></Link>)}{!rows.length && <div className="p-12 text-center text-slate-500">لا توجد هواتف بعد. أضف أول هاتف من الزر أعلاه.</div>}</div>
  </section>;
}
