import Link from 'next/link';
import { Plus, Smartphone } from 'lucide-react';
import { createClient } from '@/lib/supabase/server';

export default async function AdminProductsPage() {
  const supabase = await createClient();
  const { data: products } = await supabase.from('products').select('id,name,slug,price_usd,price_syp,stock_status,is_active,installment_enabled,brands(name)').order('created_at',{ascending:false});
  return <section className="p-6 lg:p-10"><div className="mb-8 flex items-center justify-between gap-4"><div><p className="text-sm text-sky-300">إدارة الكتالوج</p><h1 className="mt-2 text-3xl font-black">الهواتف</h1><p className="mt-2 text-slate-400">إدارة الهواتف والأسعار والتقسيط والحالة.</p></div><Link href="/admin/products/new" className="flex items-center gap-2 rounded-xl bg-sky-400 px-4 py-3 font-bold text-slate-950 hover:bg-sky-300"><Plus size={18}/> إضافة هاتف</Link></div><div className="overflow-hidden rounded-2xl border border-white/10 bg-white/[.03]"><div className="grid grid-cols-[1fr_150px_130px_110px] gap-4 border-b border-white/10 p-4 text-xs text-slate-500"><span>الهاتف</span><span>السعر</span><span>المخزون</span><span>الحالة</span></div>{(products ?? []).map((p:any)=><Link key={p.id} href={`/admin/products/${p.id}`} className="grid grid-cols-[1fr_150px_130px_110px] items-center gap-4 border-b border-white/5 p-4 hover:bg-sky-400/5"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-sky-400/10 text-sky-300"><Smartphone size={19}/></div><div><p className="font-bold">{p.name}</p><p className="text-xs text-slate-500">{p.brands?.name ?? 'بدون ماركة'}{p.installment_enabled ? ' • تقسيط' : ''}</p></div></div><div><b>{p.price_syp ? Number(p.price_syp).toLocaleString('ar-SY') : '—'}</b><p className="text-xs text-slate-500">{p.price_usd ? `$${p.price_usd}` : ''}</p></div><span className="text-sm text-slate-300">{p.stock_status === 'in_stock' ? 'متوفر' : p.stock_status === 'out_of_stock' ? 'غير متوفر' : 'قريبًا'}</span><span className={p.is_active ? 'text-sm text-emerald-300' : 'text-sm text-red-300'}>{p.is_active ? 'نشط' : 'مخفي'}</span></Link>)}{!products?.length && <div className="p-12 text-center text-slate-500">لا توجد هواتف بعد. أضف أول هاتف من الزر أعلاه.</div>}</div></section>;
}
