export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      admins: { Row: { id: string; name: string; role: string; is_active: boolean; created_at: string }; Insert: { id: string; name: string; role?: string; is_active?: boolean; created_at?: string }; Update: Partial<{ id: string; name: string; role: string; is_active: boolean; created_at: string }>; Relationships: [] };
      brands: { Row: { id: string; name: string; slug: string; created_at: string }; Insert: { id?: string; name: string; slug: string; created_at?: string }; Update: Partial<{ id: string; name: string; slug: string; created_at: string }>; Relationships: [] };
      products: { Row: { id: string; brand_id: string | null; name: string; slug: string; model: string | null; description: string | null; price_usd: number | null; price_syp: number | null; stock_quantity: number; stock_status: string; is_active: boolean; is_featured: boolean; installment_enabled: boolean; specs: Json; created_at: string; updated_at: string }; Insert: { id?: string; brand_id?: string | null; name: string; slug: string; model?: string | null; description?: string | null; price_usd?: number | null; price_syp?: number | null; stock_quantity?: number; stock_status?: string; is_active?: boolean; is_featured?: boolean; installment_enabled?: boolean; specs?: Json; created_at?: string; updated_at?: string }; Update: Partial<{ id: string; brand_id: string | null; name: string; slug: string; model: string | null; description: string | null; price_usd: number | null; price_syp: number | null; stock_quantity: number; stock_status: string; is_active: boolean; is_featured: boolean; installment_enabled: boolean; specs: Json; created_at: string; updated_at: string }>; Relationships: [] };
      product_images: { Row: { id: string; product_id: string; url: string; position: number; alt_text: string | null; is_primary: boolean; created_at: string }; Insert: { id?: string; product_id: string; url: string; position?: number; alt_text?: string | null; is_primary?: boolean; created_at?: string }; Update: Partial<{ id: string; product_id: string; url: string; position: number; alt_text: string | null; is_primary: boolean; created_at: string }>; Relationships: [] };
      installment_plans: { Row: { id: string; product_id: string; months: number; first_payment_type: string; first_payment_value: number; total_price: number | null; monthly_amount: number | null; is_active: boolean; created_at: string; updated_at: string }; Insert: { id?: string; product_id: string; months: number; first_payment_type: string; first_payment_value: number; total_price?: number | null; monthly_amount?: number | null; is_active?: boolean; created_at?: string; updated_at?: string }; Update: Partial<{ id: string; product_id: string; months: number; first_payment_type: string; first_payment_value: number; total_price: number | null; monthly_amount: number | null; is_active: boolean; created_at: string; updated_at: string }>; Relationships: [] };
      customers: { Row: { id: string; name: string; phone: string; address: string | null; telegram_user_id: number | null; telegram_chat_id: number | null; telegram_username: string | null; created_at: string }; Insert: { id?: string; name: string; phone: string; address?: string | null; telegram_user_id?: number | null; telegram_chat_id?: number | null; telegram_username?: string | null; created_at?: string }; Update: Partial<{ id: string; name: string; phone: string; address: string | null; telegram_user_id: number | null; telegram_chat_id: number | null; telegram_username: string | null; created_at: string }>; Relationships: [] };
      orders: { Row: { id: string; customer_id: string | null; product_id: string | null; installment_plan_id: string | null; status: string; notes: string | null; total_amount: number | null; first_payment: number | null; monthly_amount: number | null; months: number | null; created_at: string; updated_at: string }; Insert: { id?: string; customer_id?: string | null; product_id?: string | null; installment_plan_id?: string | null; status?: string; notes?: string | null; total_amount?: number | null; first_payment?: number | null; monthly_amount?: number | null; months?: number | null; created_at?: string; updated_at?: string }; Update: Partial<{ id: string; customer_id: string | null; product_id: string | null; installment_plan_id: string | null; status: string; notes: string | null; total_amount: number | null; first_payment: number | null; monthly_amount: number | null; months: number | null; created_at: string; updated_at: string }>; Relationships: [] };
      conversations: { Row: { id: string; customer_id: string | null; telegram_chat_id: number; status: string; last_message_at: string; assigned_to: string | null; created_at: string }; Insert: { id?: string; customer_id?: string | null; telegram_chat_id: number; status?: string; last_message_at?: string; assigned_to?: string | null; created_at?: string }; Update: Partial<{ id: string; customer_id: string | null; telegram_chat_id: number; status: string; last_message_at: string; assigned_to: string | null; created_at: string }>; Relationships: [] };
      messages: { Row: { id: string; conversation_id: string; sender_type: string; message_text: string; telegram_message_id: number | null; is_read: boolean; created_at: string }; Insert: { id?: string; conversation_id: string; sender_type: string; message_text: string; telegram_message_id?: number | null; is_read?: boolean; created_at?: string }; Update: Partial<{ id: string; conversation_id: string; sender_type: string; message_text: string; telegram_message_id: number | null; is_read: boolean; created_at: string }>; Relationships: [] };
      reviews: { Row: { id: string; product_id: string; customer_name: string; rating: number; comment: string | null; is_approved: boolean; created_at: string }; Insert: { id?: string; product_id: string; customer_name: string; rating: number; comment?: string | null; is_approved?: boolean; created_at?: string }; Update: Partial<{ id: string; product_id: string; customer_name: string; rating: number; comment: string | null; is_approved: boolean; created_at: string }>; Relationships: [] };
      settings: { Row: { id: string; key: string; value: Json; updated_at: string }; Insert: { id?: string; key: string; value?: Json; updated_at?: string }; Update: Partial<{ id: string; key: string; value: Json; updated_at: string }>; Relationships: [] };
      audit_logs: { Row: { id: string; admin_id: string | null; action: string; entity: string; entity_id: string | null; metadata: Json | null; created_at: string }; Insert: { id?: string; admin_id?: string | null; action: string; entity: string; entity_id?: string | null; metadata?: Json | null; created_at?: string }; Update: Partial<{ id: string; admin_id: string | null; action: string; entity: string; entity_id: string | null; metadata: Json | null; created_at: string }>; Relationships: [] };
    };
    Views: Record<string, never>;
    Functions: { is_admin: { Args: Record<string, never>; Returns: boolean } };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
